# Generated by Django 6.0.5 on 2026-06-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('DOB', models.DateField()),
                ('enrollment', models.IntegerField()),
                ('project_title', models.CharField()),
            ],
        ),
    ]
