# Generated by Django 6.0.5 on 2026-07-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('ptitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypro.student')),
            ],
        ),
    ]
