# Generated by Django 6.0.5 on 2026-06-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='quantity',
        ),
    ]
