# Generated by Django 6.0.5 on 2026-06-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=60),
        ),
    ]
